version: "3.8"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: akhmadwildan
      MONGO_INITDB_ROOT_PASSWORD: akhmadwildan
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example
  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: akhmadwildan
      ME_CONFIG_BASICAUTH_PASSWORD: akhmadwildan
      ME_CONFIG_MONGODB_ADMINUSERNAME: akhmadwildan
      ME_CONFIG_MONGODB_ADMINPASSWORD: akhmadwildan
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    depends_on:
      - mongodb-example
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge